### ISSUE TITLE
[FEATURE] Adds .djinrc 

### ISSUE THREAD

**Issue by catks** [catks/djin#26]
.djinrc will be loaded before any build command or task command, also some environment must be provisioned to enable executing specific tasks in each scenario, eg:

```bash
#!/bin/bash

case $DJIN_COMMAND_TYPE in
  build)
    # Some code here ...
    ;;

  task)
    # Some code here ...
    ;;
esac
```

With this some workarounds can be dropped, eg:

```yaml
release:
    local:
      run:
        - (source ~/.zshrc || true)
        - verto tag up {{args}}
        - bundle exec rake release
```
