### ISSUE TITLE
Abort execution when a depends_on task fail

### ISSUE THREAD

**Issue by catks** [catks/djin#32]
Given the following file:

```yaml
djin_version: '0.10.0'

tasks:
  my_broken_task:
    local:
      run:
        - echo 'I will break you'
        - this_doesnt_exists
       
  other:
    local:
      run:
        - echo 'I am Here'
    depends_on:
      - my_broken_task
```

The expected behavior is to abort execution when running `djin other`, but it will continue the execution and print:

```
I will break you
sh: this_doesnt_exists: command not found
I am Here
```
